spring:
  application:
    name: greeting
management:
  security:
    enabled: false
greeting:
  displayFortune: true
fortuneService:
  baseUrl: http://localhost:8081/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/